version: "3.8"
services: 
  web:
    build: .
    volumes: 
      - .:/app
    ports: 
      - 8000:8000
    image: web:app
    container_name: django_web_app
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    environment:
      - PORT=8000
  cypress:
    image: "cypress/included:3.4.0"
    depends_on:
      - web
    environment:
      - CYPRESS_baseUrl=http://localhost:8000
    working_dir: /e2e
    volumes:
      - ./:/e2e


